version: '3.8'
services:
  app:
    user: vscode
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3.9-bullseye
    volumes:
      - .:/workspace:cached # Shared workspace between host and devcontainer
      - extensions:/home/vscode/.vscode-server/extensions # Storing extensions
      - zhistory:/home/vscode/commandhistory # Persistant command line history
      - cache:/home/vscode/.cache # Caching poetry/pip wheels

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

# Volumes that are not shared between Host and Devcontainer must be listed here.
volumes:
  extensions:
  zhistory:
  cache:
