name: Lint test

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.11"

      - name: Install Python dependencies
        run: |
          poetry install
      - name: Run linting
        run: poetry run pre-commit run --all-files
