name: Pytest with code coverage

on:
  pull_request:
    branches:
      - main
      - wp-2-startpoint-anine-data

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.11"

      - name: Install python dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run coverage run -m pytest

      - name: Run coverage
        run: poetry run coverage report
