name: Pytest with code coverage

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.8"

      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.11"

      - name: Install python dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run coverage run -m pytest

      - name: Run coverage
        run: poetry run coverage xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: fpl-timeseries-data
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
